baseURL = "https://blog.shiyuanjie.cn"
languageCode = "zh-CN"
title = "Yuanjie-跑步爱好者，IT从业者。"
theme = "PaperMod"
# googleAnalytics = "G-5XEH1YLC7R"  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140
ignoreLogs = ['warning-goldmark-raw-html']


[author]
  name = "Yuanjie"

[params]
  author = "Yuanjie"
  description = "跑步爱好者，IT从业者。"
  keywords = ["测试","敏捷","跑步","项目管理","学习"]
  defaultTheme = "auto" # light, dark, auto
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true
  TocOpen = false
  env = "production" # enables GA/Utterances/Disqus etc.
  busuanzi = true # 自定义: 在自定义头部/底部插入 busuanzi 脚本 (layouts/partials/extend_head.html)
  baiduAd = "ac69e1e54b317232c0d3a881b738cfe8"
  beian = "陕ICP备20003547号-1"
  homeInfoParams = { Title = "你好，我是 Yuanjie", Content = "跑步爱好者 · IT从业者 · 记录与分享" }
  socialIcons = [
    { name = "github", url = "https://github.com/aimer1124" },
  ]
  # 可在 layouts/partials/extend_head.html 中引入 busuanzi 与自定义统计脚本
  # 如果需要自定义 CSS/JS:
  # assets/css/extended/ 或 assets/js/extended/

  # 友情链接 (PaperMod 无内置 links 区域, 可在自定义 widget 或页面里用数据文件; 暂保留原结构供后续迁移)

## 友情链接，可以多个
[[params.links]]
 title = "我的小工具"
 name = "我的小工具"
 url = "https://www.shiyuanjie.cn/tools/"

[[params.links]]
 title = "利用21天时间完成一本Mini书"
 name = "利用21天时间完成一本Mini书"
 url = "https://www.shiyuanjie.cn/posts/Upgrade/%E5%88%A9%E7%94%A821%E5%A4%A9%E7%9A%84%E5%AE%8C%E6%88%90%E4%B8%80%E6%9C%ACMini%E4%B9%A6/"

[[params.links]]
 title = "练字记录"
 name = "练字记录"
 url = "https://aimer1124.github.io/practice-character/"

[[params.links]]
 title = "GR记录"
 name = "GR记录"
 url = "https://aimer1124.github.io/graphic-recorder/"

[[params.links]]
 title = "PM的问题集"
 name = "PM的问题集"
 url = "https://aimer1124.github.io/100-questions-to-pm/"

[[params.links]]
 title = "网站时间线Timeline"
 name = "网站时间线Timeline"
 url = "https://www.shiyuanjie.cn/posts/Blog/%E7%AB%99%E7%82%B9%E6%90%AD%E5%BB%BA%E8%BF%87%E7%A8%8B/"

## 侧边栏广告位
#[[params.ads]]
# title = "幕布: 极简大纲笔记 | 一键生成思维导图"
# url = "https://mubu.com/inv/2370809"
# img = "https://mubu.com/asset/img/logo/text-0f5be2e426.png"
#[[params.ads]]
# title = "[极客时间]视觉笔记入门课"
# url = "https://time.geekbang.org/column/intro/306?tab=catalog&code=EgKm1rU5f1GGwIV5DX9vfYw2cYufFyXDkdknOoV8d3k%3D&utm_term=SPoster"
# img = "https://static001.geekbang.org/resource/image/57/df/57a4a47bd98eb1f01b8a38182e6f2bdf.png?x-oss-process=image/resize,m_fill,h_89,w_89"
#[[params.ads]]
# title = "【上云必备】上云仅¥102/年"
# url = "https://www.aliyun.com/activity/daily/cloud?userCode=1cttmhqm"
# img = "https://img.alicdn.com/tfs/TB1nkoQDlv0gK0jSZKbXXbK2FXa-440-240.jpg"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "aimer1124/comments-blog"
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "monokai"
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

## 配置网站菜单
[menu]

 [[menu.main]]
   identifier = "tools"
   name = "小工具"
   url = "/tools/"
   weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
